In [34]:
import numpy as np
import torch

In [35]:
d1 = np.array([[1,2,3,4], [2,3,4,5]])

In [36]:
d1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [37]:
e = np.empty((3,3))
e

array([[6.17779239e-31, 1.23555848e-30, 3.08889620e-31],
       [1.23555848e-30, 2.68733969e-30, 8.34001973e-31],
       [3.08889620e-31, 8.34001973e-31, 4.78778910e-31]])

In [38]:
d2 = np.arange(12)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
d2[2:3]

array([ 2,  5,  8, 11])

In [25]:
copy  = d1.flatten()
copy.squeeze()
copy

array([1, 2, 3, 4, 2, 3, 4, 5])

In [33]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4).reshape(2, 2)

c = np.append(x, y, axis=0)
c

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [44]:
x = torch.randn(2,3)
x

tensor([[ 0.2721,  0.5659,  0.7769],
        [-0.7199, -1.2825,  0.5479]])

In [51]:
mask = x>0
torch.masked_select(x, mask)

tensor([0.2721, 0.5659, 0.7769, 0.5479])

In [54]:
torch.nonzero(mask)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 2]])

In [67]:
a = torch.linspace(0, 10, 10).view((2, 5))
a

tensor([[ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444],
        [ 5.5556,  6.6667,  7.7778,  8.8889, 10.0000]])

In [75]:
b = a.norm(p=1)
b

tensor(50.)